### PR TITLE
dns-message

### LINKED ISSUE #58: DoH client
- [x] I am using the latest version of `Pixiv-MultiPlatform` (required)
- [x] I can reliably reproduce this bug (required)
- [x] I confirm that I will be notified immediately when developers reply to this issue (required)
- [x] I have the ability to download APKs directly from CI once the bug fix is available (optional)

# 1. Bug Description

DoH request is invalid.

Image

# 2. How to Reproduce

Enable SNI bypass and DoH.

[dns-json](https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/dns-json/) is unstandard format by Cloudflare and not supported by other DoH resolvers. Please use RFC 1035 [dns-message](https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/dns-wireformat/) instead.

### PR DESCRIPTION
**Pull request by UjuiUjuMandan**
Close #58.

### CODE REVIEW

**Comment by magic-cucumber** [comment]
run ./gradlew spotlessApply and commit again

File: composeApp/src/desktopMain/kotlin/top/kagg886/pmf/backend/auto-fuck-china-desktop.kt [hunk 1]
```diff
@@ -91,7 +91,7 @@ private data class SNIReplaceDNS(
         val data = try {
             val host = when {
                 hostname.endsWith("pixiv.net") -> {
-                    "www.pixivision.net"
+                    "pixiv.net"
                 }
```
Comment (magic-cucumber) [inline composeApp/src/desktopMain/kotlin/top/kagg886/pmf/backend/auto-fuck-china-desktop.kt]: pixivvision.net is accessible from **mainland china** and shares the same IP address as pixiv.net, using this domain allows you to use certain restricted DoH services, such as Alibaba Cloud DoH...

File: composeApp/src/androidMain/kotlin/top/kagg886/pmf/backend/auto-fuck-china-android.kt [hunk 2]
```diff
@@ -91,7 +91,7 @@ private data class SNIReplaceDNS(
         val data = try {
             val host = when {
                 hostname.endsWith("pixiv.net") -> {
-                    "www.pixivision.net"
+                    "pixiv.net"
```
Comment (magic-cucumber) [inline composeApp/src/androidMain/kotlin/top/kagg886/pmf/backend/auto-fuck-china-android.kt]: pixivvision.net is accessible from mainland china and shares the same IP address as pixiv.net, using this domain allows you to use certain restricted DoH services, such as Alibaba Cloud DoH...

**Review by magic-cucumber — CHANGES_REQUESTED** [review]
some questions.

File: composeApp/src/desktopMain/kotlin/top/kagg886/pmf/backend/auto-fuck-china-desktop.kt (hunk 1 above)
Comment (UjuiUjuMandan) [reply composeApp/src/desktopMain/kotlin/top/kagg886/pmf/backend/auto-fuck-china-desktop.kt]: > shares the same IP address as pixiv.net,

No longer. pixiv is moving more domains to Cloudflare proxy.

https://dns.google/query?name=www.pixivision.net

> sing this domain allows you to use certain restricted DoH services, such as Alibaba Cloud DoH.

You can still use the `.cdn.cloudflare.net` trick.

**Review by magic-cucumber — DISMISSED** [review]

**Comment by UjuiUjuMandan** [comment]
Dns.SYSTEM now looks up `pixiv.net.cdn.cloudflare.net` to retrieve origin server IP addresses while circumventing hijacking.

**Review by magic-cucumber — APPROVED** [review]
